apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taxi-data-indexer.fullname" . }}-secrets
  labels:
    {{- include "taxi-data-indexer.labels" . | nindent 4 }}
type: Opaque
data:
  opensearch-password: {{ .Values.secrets.opensearch.password | b64enc | quote }}

