# Prometheus Web Configuration for TLS
# This file is used when TLS is enabled

tls_server_config:
  cert_file: /etc/prometheus/certs/localhost.crt
  key_file: /etc/prometheus/certs/localhost.key

http_server_config:
  http2: true

