apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch.fullname" . }}-secrets
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.opensearch.adminPassword | b64enc | quote }}

