apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taxi-data-processor.fullname" . }}-secrets
  labels:
    {{- include "taxi-data-processor.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}

